import re, sys, os

root = sys.argv[1]
rc = os.path.join(root, 'PowerEditor/src/Notepad_plus.rc')
src = open(rc, encoding='utf-8', errors='replace').read()

m = re.search(r'^IDR_[A-Z0-9_]*MENU\s+MENU\b', src, re.M)
block = src[m.start():] if m else src

stack, rows, depth = [], [], 0
for line in block.splitlines():
    t = line.strip()
    if t == 'BEGIN':
        depth += 1; continue
    if t == 'END':
        depth -= 1
        if stack: stack.pop()
        if depth <= 0: break
        continue
    mp = re.match(r'POPUP\s+"([^"]+)"', t)
    if mp:
        stack.append(mp.group(1).replace('&', '')); continue
    mi = re.match(r'MENUITEM\s+"([^"]+)"\s*,\s*(IDM_[A-Z0-9_]+)', t)
    if mi:
        label = mi.group(1).replace('&', '').split('\\t')[0].strip()
        rows.append((list(stack), label, mi.group(2)))

done = set()
impl = os.path.join(root, 'macos/implemented.txt')
if os.path.exists(impl):
    for line in open(impl):
        line = line.split('#')[0].strip()
        if line:
            done.add(line)

groups = {}
for path, label, cid in rows:
    top = path[0] if path else '(root)'
    groups.setdefault(top, []).append((path[1:], label, cid))

total = len(rows)
total_done = sum(1 for _, _, c in rows if c in done)

out = []
out.append('# Notepad++ feature parity on macOS\n')
out.append('Generated by `macos/gen_features.sh` from the Windows menu resource\n'
           '(`PowerEditor/src/Notepad_plus.rc`), so this list cannot drift from upstream.\n'
           'It measures one thing: how much of the Windows menus this port implements.\n'
           'What the port adds *on top of* the Windows menus is under\n'
           '[Beyond the Windows menus](#beyond-the-windows-menus) at the end.\n')
out.append(f'**{total_done} of {total} menu commands implemented '
           f'({100.0*total_done/total:.1f}%).**\n')

out.append('## Coverage by menu\n')
out.append('| Menu | Done | Total | |')
out.append('|---|---:|---:|---|')
for top in sorted(groups, key=lambda k: -len(groups[k])):
    items = groups[top]
    d = sum(1 for _, _, c in items if c in done)
    filled = int(round(10.0 * d / len(items)))
    bar = '█' * filled + '·' * (10 - filled)
    out.append(f'| {top} | {d} | {len(items)} | `{bar}` |')
out.append('')
out.append('The Plugins menu counts 1 because the Windows menu resource itself carries a\n'
           'single static command there — plugins add their entries at run time. The\n'
           'equivalents of the most-used plugins are built into this port; see\n'
           '[Beyond the Windows menus](#beyond-the-windows-menus).\n')

out.append('## Commands\n')
for top in sorted(groups, key=lambda k: -len(groups[k])):
    items = groups[top]
    d = sum(1 for _, _, c in items if c in done)
    out.append(f'### {top} — {d}/{len(items)}\n')
    out.append('| | Command | ID |')
    out.append('|---|---|---|')
    for sub, label, cid in items:
        mark = '✅' if cid in done else '☐'
        name = ' › '.join(sub + [label]) if sub else label
        out.append(f'| {mark} | {name} | `{cid}` |')
    out.append('')

out.append('''## Beyond the Windows menus

Everything above is parity with the Windows version. These are the port's own
additions, kept in this hand-maintained block of `macos/gen_features.py`:

**Tools** (the Windows Tools menu stops at MD5/SHA digests and command-line
arguments):

- Hashes: bcrypt, scrypt, Argon2 and PBKDF2 (with cost/salt parameters), and
  the SHA-3 family — each with the same generate / from-file / per-line
  commands the classic digests have.
- Base64, Base58 and Base32 encode/decode, one window per base.
- Password Generator.
- HTTP Request: compose and send requests (libcurl), import and export
  `curl` command lines.

**Plugins, built in** — stand-ins for the plugins Windows users install:

- JSON viewer (format, sort, tree view)
- Compare (two-document diff)
- XML tools
- FTP client (profiles, remote browsing)
- NppExec-style script console and Run commands
- MIME Tools (Quoted-printable, URL encoding, SAML decode; its Base64 is
  Tools > Base's job and is not doubled)
- Converter (ASCII/HEX both ways, the Conversion Panel for one value in
  every base)
- NppExport (the styled text as RTF and HTML, to a file or the clipboard)
- Spell checking as DSpellCheck arranges it, on the system engine: squiggles
  as you type - in code only comments and strings - suggestions in the
  context menu, Ignore and Learn, every installed dictionary
- Markdown Preview (MarkdownViewer++'s job): the document rendered live in a
  docked panel - CommonMark by cmark, GFM tables by a pre-pass

**Third-party plugins** load the way they do on Windows: a dynamic library in
the plugins folder with the C interface of
[macos/plugin-sdk](../macos/plugin-sdk/README.md) - Notepad++'s
PluginInterface.h translated to macOS, Scintilla messages and all.

**Only a Mac could** - where Windows plugins leaned on Windows, this port
leans the other way:

- The `nppmac` command line tool: files (at a line), folders as workspaces,
  standard input; installed into /usr/local/bin from the Tools menu.
- Paste Image as Text: the clipboard's image through the system's text
  recognizer (Vision), at the caret; Recognize Text in File reads an image
  or a PDF, page by page, into a new document.
- QR codes both ways: the selection as a code, the clipboard's code as text.
- Spell checking by the system engine, with every installed dictionary.

**And besides the menus:**

- Selected numbers: the context menu (and Edit > Selected Numbers) writes a
  selected set of numbers' sum, average, minimum, maximum or count after them
  and sorts them in place; Edit >
  Calculate (Cmd+=) writes a formula's value after its "=" - the selected
  formula or the one being typed - with functions (sin, ln, log, sqrt...),
  degrees, constants and percent.

- When a file's name says nothing, a trained model recognises the language of
  the text — 91 languages, no hand-written rules.
- The interface is localized into ~90 languages, the port's own strings
  included, using Notepad++'s own translation files.
''')

open(os.path.join(root, 'macos/FEATURES.md'), 'w').write('\n'.join(out))
print(f'wrote macos/FEATURES.md — {total_done}/{total} commands ({100.0*total_done/total:.1f}%)')
